/*
 * generated by Xtext
 */
package roadblock.xtext.ibl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IblRuntimeModule extends roadblock.xtext.ibl.AbstractIblRuntimeModule {

}
