/*
* generated by Xtext
*/
package roadblock.xtext.ibl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IblUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return roadblock.xtext.ibl.ui.internal.IblActivator.getInstance().getInjector("roadblock.xtext.ibl.Ibl");
	}
	
}
