/**
 * generated by Xtext
 */
package roadblock.xtext.ibl.ui.contentassist;

import roadblock.xtext.ibl.ui.contentassist.AbstractIblProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class IblProposalProvider extends AbstractIblProposalProvider {
}
