# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "halvards/lubuntu1604"
  config.vm.box_version = "20160611.0.0"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision "shell", keep_color: true, inline: <<-SHELL
     wget http://ftp.gnu.org/gnu/gzip/gzip-1.3.12.tar -O ibw.exec
   SHELL
end
