# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "ibw"
	vb.gui = true
	vb.memory = 4096
	vb.cpus = 4
  end

  config.vm.provision "file", source: "./ibw_icon.png", destination: "./ibw_icon.png"
  config.vm.provision "file", source: "./ibw.desktop", destination: "./Desktop/ibw.desktop"
  config.vm.provision "shell", keep_color: true, path: "provision_env.sh"

end

