/**
 * generated by Xtext
 */
package roadblock.xtext.ibl.validation;

import roadblock.xtext.ibl.validation.AbstractIblValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class IblValidator extends AbstractIblValidator {
}
