/**
 *
 * $Id$
 */
package roadblock.emf.ibl.Ibl.validation;

import roadblock.emf.ibl.Ibl.ConcentrationUnit;
import roadblock.emf.ibl.Ibl.RelationalOperator;

/**
 * A sample validator interface for {@link roadblock.emf.ibl.Ibl.ConcentrationConstraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConcentrationConstraintValidator {
	boolean validate();

	boolean validateOperator(RelationalOperator value);
	boolean validateValue(double value);
	boolean validateUnit(ConcentrationUnit value);
}
