/**
 *
 * $Id$
 */
package roadblock.emf.ibl.Ibl.validation;

import java.util.List;

import roadblock.emf.ibl.Ibl.MolecularSpecies;
import roadblock.emf.ibl.Ibl.Rule;

/**
 * A sample validator interface for {@link roadblock.emf.ibl.Ibl.FlatModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlatModelValidator {
	boolean validate();

	boolean validateMoleculeList(List<MolecularSpecies> value);
	boolean validateRuleList(List<Rule> value);
}
