/**
 *
 * $Id$
 */
package roadblock.emf.ibl.Ibl.validation;

import java.util.List;

import roadblock.emf.ibl.Ibl.ATGCDirective;
import roadblock.emf.ibl.Ibl.Cell;
import roadblock.emf.ibl.Ibl.Device;
import roadblock.emf.ibl.Ibl.Kinetics;
import roadblock.emf.ibl.Ibl.MolecularSpecies;
import roadblock.emf.ibl.Ibl.Region;
import roadblock.emf.ibl.Ibl.Rule;

/**
 * A sample validator interface for {@link roadblock.emf.ibl.Ibl.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateDisplayName(String value);
	boolean validateProcessList(List<Kinetics> value);
	boolean validateCellList(List<Cell> value);
	boolean validateRuleList(List<Rule> value);
	boolean validateDeviceList(List<Device> value);
	boolean validateMoleculeList(List<MolecularSpecies> value);
	boolean validateATGCcommandList(List<ATGCDirective> value);
	boolean validateID(String value);
	boolean validateRegionList(List<Region> value);
}
