/**
 *
 * $Id$
 */
package roadblock.emf.ibl.Ibl.validation;

import roadblock.emf.ibl.Ibl.ConcentrationUnit;
import roadblock.emf.ibl.Ibl.RateUnit;

/**
 * A sample validator interface for
 * {@link roadblock.emf.ibl.Ibl.MolecularSpecies}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MolecularSpeciesValidator {
	boolean validate();

	boolean validateDisplayName(String value);

	boolean validateURI(String value);

	boolean validateAmount(double value);

	boolean validateUnit(ConcentrationUnit value);

	boolean validateDegradationRate(Double value);

	boolean validateDegradationRate(double value);

	boolean validateBindingRate(Double value);

	boolean validateUnbindingRate(Double value);

	boolean validateBiologicalType(String value);

	boolean validateSequence(String value);

	boolean validateDegradationRateUnit(RateUnit value);

	boolean validateBindingRateUnit(RateUnit value);

	boolean validateUnbindingRateUnit(RateUnit value);

	boolean validateID(String value);
}
