/**
 *
 * $Id$
 */
package roadblock.emf.ibl.Ibl.validation;

import java.util.List;

import roadblock.emf.ibl.Ibl.IProbabilityConstraint;
import roadblock.emf.ibl.Ibl.ITimeConstraint;
import roadblock.emf.ibl.Ibl.PropertyInitialCondition;

/**
 * A sample validator interface for {@link roadblock.emf.ibl.Ibl.ProbabilityProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProbabilityPropertyValidator {
	boolean validate();

	boolean validateTimeConstraint(ITimeConstraint value);
	boolean validateProbabilityConstraint(IProbabilityConstraint value);
	boolean validateInitialConditions(List<PropertyInitialCondition> value);
}
