/**
 *
 * $Id$
 */
package roadblock.emf.ibl.Ibl.validation;

import java.util.List;

import roadblock.emf.ibl.Ibl.ConcentrationConstraint;
import roadblock.emf.ibl.Ibl.PropertyInitialCondition;
import roadblock.emf.ibl.Ibl.TimeInstant;

/**
 * A sample validator interface for {@link roadblock.emf.ibl.Ibl.RewardProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RewardPropertyValidator {
	boolean validate();

	boolean validateVariableName(String value);
	boolean validateTimeConstraint(TimeInstant value);
	boolean validateConcentrationConstraint(ConcentrationConstraint value);
	boolean validateInitialConditions(List<PropertyInitialCondition> value);
}
