/*
* generated by Xtext
*/
package roadblock.xtext.ibl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import roadblock.xtext.ibl.services.IblGrammarAccess;

public class IblParser extends AbstractContentAssistParser {
	
	@Inject
	private IblGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected roadblock.xtext.ibl.ui.contentassist.antlr.internal.InternalIblParser createParser() {
		roadblock.xtext.ibl.ui.contentassist.antlr.internal.InternalIblParser result = new roadblock.xtext.ibl.ui.contentassist.antlr.internal.InternalIblParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelMemberAccess().getAlternatives(), "rule__ModelMember__Alternatives");
					put(grammarAccess.getFunctionTypeAccess().getAlternatives(), "rule__FunctionType__Alternatives");
					put(grammarAccess.getFunctionBodyTypeAccess().getAlternatives(), "rule__FunctionBodyType__Alternatives");
					put(grammarAccess.getFunctionBodyMemberAccess().getAlternatives(), "rule__FunctionBodyMember__Alternatives");
					put(grammarAccess.getFunctionParameterMemberAccess().getAlternatives_0(), "rule__FunctionParameterMember__Alternatives_0");
					put(grammarAccess.getFunctionParameterMemberAccess().getTypeAlternatives_0_1_2_0(), "rule__FunctionParameterMember__TypeAlternatives_0_1_2_0");
					put(grammarAccess.getFunctionParameterScopeAccess().getAlternatives(), "rule__FunctionParameterScope__Alternatives");
					put(grammarAccess.getDeviceMembersAccess().getAlternatives(), "rule__DeviceMembers__Alternatives");
					put(grammarAccess.getVariableTypeAccess().getAlternatives(), "rule__VariableType__Alternatives");
					put(grammarAccess.getVariableAttributeAccess().getAlternatives_1(), "rule__VariableAttribute__Alternatives_1");
					put(grammarAccess.getVariableDefinitionAccess().getDefinitionAlternatives_1_0(), "rule__VariableDefinition__DefinitionAlternatives_1_0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getAlternatives_2(), "rule__VariableDefinitionBuiltIn__Alternatives_2");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getConstructorAlternatives_3_2_0(), "rule__VariableDefinitionBuiltIn__ConstructorAlternatives_3_2_0");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getTypeAlternatives_1_2_0(), "rule__VariableDefinitionCollection__TypeAlternatives_1_2_0");
					put(grammarAccess.getCollectionIDAccess().getAlternatives(), "rule__CollectionID__Alternatives");
					put(grammarAccess.getVariableAssignmentObjectAccess().getAlternatives(), "rule__VariableAssignmentObject__Alternatives");
					put(grammarAccess.getVariableExpressionObjectAccess().getAlternatives(), "rule__VariableExpressionObject__Alternatives");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getAlternatives(), "rule__AtomicVariableExpressionObject__Alternatives");
					put(grammarAccess.getVariableExpressionOperatorAccess().getAlternatives(), "rule__VariableExpressionOperator__Alternatives");
					put(grammarAccess.getRuleDefinitionAccess().getAlternatives_5(), "rule__RuleDefinition__Alternatives_5");
					put(grammarAccess.getRuleObjectAccess().getAlternatives(), "rule__RuleObject__Alternatives");
					put(grammarAccess.getPropertyDefinitionAccess().getPropertyAlternatives_2_0(), "rule__PropertyDefinition__PropertyAlternatives_2_0");
					put(grammarAccess.getProbabilityPropertyAccess().getAlternatives_2(), "rule__ProbabilityProperty__Alternatives_2");
					put(grammarAccess.getProbabilityPropertyAccess().getAlternatives_2_0_0(), "rule__ProbabilityProperty__Alternatives_2_0_0");
					put(grammarAccess.getProbabilityPropertyAccess().getAlternatives_2_0_0_0(), "rule__ProbabilityProperty__Alternatives_2_0_0_0");
					put(grammarAccess.getProbabilityPropertyAccess().getAlternatives_2_0_0_1_0(), "rule__ProbabilityProperty__Alternatives_2_0_0_1_0");
					put(grammarAccess.getProbabilityPropertyAccess().getAlternatives_2_0_1(), "rule__ProbabilityProperty__Alternatives_2_0_1");
					put(grammarAccess.getProbabilityPropertyAccess().getAlternatives_2_1(), "rule__ProbabilityProperty__Alternatives_2_1");
					put(grammarAccess.getStateFormulaAccess().getAlternatives(), "rule__StateFormula__Alternatives");
					put(grammarAccess.getStateFormulaAccess().getAlternatives_2_2(), "rule__StateFormula__Alternatives_2_2");
					put(grammarAccess.getTimeInstantAccess().getAlternatives_1(), "rule__TimeInstant__Alternatives_1");
					put(grammarAccess.getRewardTimeInstantAccess().getAlternatives_1(), "rule__RewardTimeInstant__Alternatives_1");
					put(grammarAccess.getProbabilityConstraintAccess().getAlternatives_2(), "rule__ProbabilityConstraint__Alternatives_2");
					put(grammarAccess.getConcentrationConstraintAccess().getAlternatives(), "rule__ConcentrationConstraint__Alternatives");
					put(grammarAccess.getREALAccess().getAlternatives(), "rule__REAL__Alternatives");
					put(grammarAccess.getUnitIntervalAccess().getAlternatives(), "rule__UnitInterval__Alternatives");
					put(grammarAccess.getDecimalAccess().getAlternatives_0(), "rule__Decimal__Alternatives_0");
					put(grammarAccess.getDecimalExpAccess().getAlternatives_0(), "rule__DecimalExp__Alternatives_0");
					put(grammarAccess.getDecimalExpAccess().getAlternatives_3(), "rule__DecimalExp__Alternatives_3");
					put(grammarAccess.getDecimalExpAccess().getAlternatives_4(), "rule__DecimalExp__Alternatives_4");
					put(grammarAccess.getTimeUnitAccess().getAlternatives(), "rule__TimeUnit__Alternatives");
					put(grammarAccess.getFluxUnitAccess().getAlternatives(), "rule__FluxUnit__Alternatives");
					put(grammarAccess.getConcentrationUnitAccess().getAlternatives(), "rule__ConcentrationUnit__Alternatives");
					put(grammarAccess.getUnitAccess().getAlternatives(), "rule__Unit__Alternatives");
					put(grammarAccess.getRelationalOperatorAccess().getAlternatives(), "rule__RelationalOperator__Alternatives");
					put(grammarAccess.getBooleanOperatorAccess().getAlternatives(), "rule__BooleanOperator__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getImportStatementAccess().getGroup(), "rule__ImportStatement__Group__0");
					put(grammarAccess.getFunctionDefinitionAccess().getGroup(), "rule__FunctionDefinition__Group__0");
					put(grammarAccess.getFunctionDefinitionAccess().getGroup_5(), "rule__FunctionDefinition__Group_5__0");
					put(grammarAccess.getFunctionDefinitionAccess().getGroup_5_2(), "rule__FunctionDefinition__Group_5_2__0");
					put(grammarAccess.getProcessBodyAccess().getGroup(), "rule__ProcessBody__Group__0");
					put(grammarAccess.getProcessBodyAccess().getGroup_3(), "rule__ProcessBody__Group_3__0");
					put(grammarAccess.getProcessBodyAccess().getGroup_3_1(), "rule__ProcessBody__Group_3_1__0");
					put(grammarAccess.getSystemBodyAccess().getGroup(), "rule__SystemBody__Group__0");
					put(grammarAccess.getSystemBodyAccess().getGroup_3(), "rule__SystemBody__Group_3__0");
					put(grammarAccess.getSystemBodyAccess().getGroup_3_1(), "rule__SystemBody__Group_3_1__0");
					put(grammarAccess.getPlasmidBodyAccess().getGroup(), "rule__PlasmidBody__Group__0");
					put(grammarAccess.getPlasmidBodyAccess().getGroup_3(), "rule__PlasmidBody__Group_3__0");
					put(grammarAccess.getPlasmidBodyAccess().getGroup_3_1(), "rule__PlasmidBody__Group_3_1__0");
					put(grammarAccess.getChromosomeBodyAccess().getGroup(), "rule__ChromosomeBody__Group__0");
					put(grammarAccess.getChromosomeBodyAccess().getGroup_3(), "rule__ChromosomeBody__Group_3__0");
					put(grammarAccess.getChromosomeBodyAccess().getGroup_3_1(), "rule__ChromosomeBody__Group_3_1__0");
					put(grammarAccess.getCellBodyAccess().getGroup(), "rule__CellBody__Group__0");
					put(grammarAccess.getCellBodyAccess().getGroup_3(), "rule__CellBody__Group_3__0");
					put(grammarAccess.getCellBodyAccess().getGroup_3_1(), "rule__CellBody__Group_3_1__0");
					put(grammarAccess.getRegionBodyAccess().getGroup(), "rule__RegionBody__Group__0");
					put(grammarAccess.getRegionBodyAccess().getGroup_3(), "rule__RegionBody__Group_3__0");
					put(grammarAccess.getRegionBodyAccess().getGroup_3_1(), "rule__RegionBody__Group_3_1__0");
					put(grammarAccess.getCustomFunctionBodyAccess().getGroup(), "rule__CustomFunctionBody__Group__0");
					put(grammarAccess.getCustomFunctionBodyAccess().getGroup_3(), "rule__CustomFunctionBody__Group_3__0");
					put(grammarAccess.getCustomFunctionBodyAccess().getGroup_3_1(), "rule__CustomFunctionBody__Group_3_1__0");
					put(grammarAccess.getFunctionParameterMemberAccess().getGroup(), "rule__FunctionParameterMember__Group__0");
					put(grammarAccess.getFunctionParameterMemberAccess().getGroup_0_1(), "rule__FunctionParameterMember__Group_0_1__0");
					put(grammarAccess.getFunctionParameterMemberAccess().getGroup_2(), "rule__FunctionParameterMember__Group_2__0");
					put(grammarAccess.getFunctionUseMemberAccess().getGroup(), "rule__FunctionUseMember__Group__0");
					put(grammarAccess.getDeviceDefinitionAccess().getGroup(), "rule__DeviceDefinition__Group__0");
					put(grammarAccess.getDeviceDefinitionAccess().getGroup_12(), "rule__DeviceDefinition__Group_12__0");
					put(grammarAccess.getDeviceDefinitionAccess().getGroup_13(), "rule__DeviceDefinition__Group_13__0");
					put(grammarAccess.getProcessInstantiationAccess().getGroup(), "rule__ProcessInstantiation__Group__0");
					put(grammarAccess.getProcessInstantiationAccess().getGroup_3(), "rule__ProcessInstantiation__Group_3__0");
					put(grammarAccess.getProcessInstantiationAccess().getGroup_3_4(), "rule__ProcessInstantiation__Group_3_4__0");
					put(grammarAccess.getProcessInstantiationAccess().getGroup_3_4_1(), "rule__ProcessInstantiation__Group_3_4_1__0");
					put(grammarAccess.getSystemInstantiationAccess().getGroup(), "rule__SystemInstantiation__Group__0");
					put(grammarAccess.getSystemInstantiationAccess().getGroup_3(), "rule__SystemInstantiation__Group_3__0");
					put(grammarAccess.getSystemInstantiationAccess().getGroup_3_4(), "rule__SystemInstantiation__Group_3_4__0");
					put(grammarAccess.getSystemInstantiationAccess().getGroup_3_4_1(), "rule__SystemInstantiation__Group_3_4_1__0");
					put(grammarAccess.getPlasmidInstantiationAccess().getGroup(), "rule__PlasmidInstantiation__Group__0");
					put(grammarAccess.getPlasmidInstantiationAccess().getGroup_3(), "rule__PlasmidInstantiation__Group_3__0");
					put(grammarAccess.getPlasmidInstantiationAccess().getGroup_3_4(), "rule__PlasmidInstantiation__Group_3_4__0");
					put(grammarAccess.getPlasmidInstantiationAccess().getGroup_3_4_1(), "rule__PlasmidInstantiation__Group_3_4_1__0");
					put(grammarAccess.getChromosomeInstantiationAccess().getGroup(), "rule__ChromosomeInstantiation__Group__0");
					put(grammarAccess.getChromosomeInstantiationAccess().getGroup_3(), "rule__ChromosomeInstantiation__Group_3__0");
					put(grammarAccess.getChromosomeInstantiationAccess().getGroup_3_4(), "rule__ChromosomeInstantiation__Group_3_4__0");
					put(grammarAccess.getChromosomeInstantiationAccess().getGroup_3_4_1(), "rule__ChromosomeInstantiation__Group_3_4_1__0");
					put(grammarAccess.getCellInstantiationAccess().getGroup(), "rule__CellInstantiation__Group__0");
					put(grammarAccess.getCellInstantiationAccess().getGroup_3(), "rule__CellInstantiation__Group_3__0");
					put(grammarAccess.getCellInstantiationAccess().getGroup_3_4(), "rule__CellInstantiation__Group_3_4__0");
					put(grammarAccess.getCellInstantiationAccess().getGroup_3_4_1(), "rule__CellInstantiation__Group_3_4_1__0");
					put(grammarAccess.getVariableComplexAccess().getGroup(), "rule__VariableComplex__Group__0");
					put(grammarAccess.getVariableComplexAccess().getGroup_2(), "rule__VariableComplex__Group_2__0");
					put(grammarAccess.getVariableAttributeAccess().getGroup(), "rule__VariableAttribute__Group__0");
					put(grammarAccess.getVariableDefinitionAccess().getGroup(), "rule__VariableDefinition__Group__0");
					put(grammarAccess.getVariableDefinitionAccess().getGroup_2(), "rule__VariableDefinition__Group_2__0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getGroup(), "rule__VariableDefinitionBuiltIn__Group__0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getGroup_3(), "rule__VariableDefinitionBuiltIn__Group_3__0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getGroup_3_4(), "rule__VariableDefinitionBuiltIn__Group_3_4__0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getGroup_3_4_1(), "rule__VariableDefinitionBuiltIn__Group_3_4_1__0");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getGroup(), "rule__VariableDefinitionUserDefined__Group__0");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getGroup_3(), "rule__VariableDefinitionUserDefined__Group_3__0");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getGroup_3_4(), "rule__VariableDefinitionUserDefined__Group_3_4__0");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getGroup_3_4_1(), "rule__VariableDefinitionUserDefined__Group_3_4_1__0");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getGroup(), "rule__VariableDefinitionCollection__Group__0");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getGroup_1(), "rule__VariableDefinitionCollection__Group_1__0");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getGroup_2(), "rule__VariableDefinitionCollection__Group_2__0");
					put(grammarAccess.getVariableDefinitionBasicAccess().getGroup(), "rule__VariableDefinitionBasic__Group__0");
					put(grammarAccess.getParameterAssignmentAccess().getGroup(), "rule__ParameterAssignment__Group__0");
					put(grammarAccess.getVariableAssignmentAccess().getGroup(), "rule__VariableAssignment__Group__0");
					put(grammarAccess.getVariableAssignmentObjectAccess().getGroup_0(), "rule__VariableAssignmentObject__Group_0__0");
					put(grammarAccess.getVariableExpressionAccess().getGroup(), "rule__VariableExpression__Group__0");
					put(grammarAccess.getVariableExpressionAccess().getGroup_2(), "rule__VariableExpression__Group_2__0");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getGroup_0(), "rule__AtomicVariableExpressionObject__Group_0__0");
					put(grammarAccess.getCompoundVariableExpressionObjectAccess().getGroup(), "rule__CompoundVariableExpressionObject__Group__0");
					put(grammarAccess.getRuleDefinitionAccess().getGroup(), "rule__RuleDefinition__Group__0");
					put(grammarAccess.getRuleDefinitionAccess().getGroup_4(), "rule__RuleDefinition__Group_4__0");
					put(grammarAccess.getRuleDefinitionAccess().getGroup_4_1(), "rule__RuleDefinition__Group_4_1__0");
					put(grammarAccess.getRuleDefinitionAccess().getGroup_6(), "rule__RuleDefinition__Group_6__0");
					put(grammarAccess.getRuleDefinitionAccess().getGroup_6_1(), "rule__RuleDefinition__Group_6_1__0");
					put(grammarAccess.getRuleObjectAccess().getGroup_0(), "rule__RuleObject__Group_0__0");
					put(grammarAccess.getATGCDefinitionAccess().getGroup(), "rule__ATGCDefinition__Group__0");
					put(grammarAccess.getATGCDefinitionAccess().getGroup_5(), "rule__ATGCDefinition__Group_5__0");
					put(grammarAccess.getPropertyDefinitionAccess().getGroup(), "rule__PropertyDefinition__Group__0");
					put(grammarAccess.getProbabilityPropertyAccess().getGroup(), "rule__ProbabilityProperty__Group__0");
					put(grammarAccess.getProbabilityPropertyAccess().getGroup_2_0(), "rule__ProbabilityProperty__Group_2_0__0");
					put(grammarAccess.getProbabilityPropertyAccess().getGroup_2_0_0_1(), "rule__ProbabilityProperty__Group_2_0_0_1__0");
					put(grammarAccess.getProbabilityPropertyAccess().getGroup_4(), "rule__ProbabilityProperty__Group_4__0");
					put(grammarAccess.getProbabilityPropertyAccess().getGroup_4_2(), "rule__ProbabilityProperty__Group_4_2__0");
					put(grammarAccess.getRewardPropertyAccess().getGroup(), "rule__RewardProperty__Group__0");
					put(grammarAccess.getRewardPropertyAccess().getGroup_8(), "rule__RewardProperty__Group_8__0");
					put(grammarAccess.getRewardPropertyAccess().getGroup_8_2(), "rule__RewardProperty__Group_8_2__0");
					put(grammarAccess.getStateExpressionAccess().getGroup(), "rule__StateExpression__Group__0");
					put(grammarAccess.getStateFormulaAccess().getGroup_0(), "rule__StateFormula__Group_0__0");
					put(grammarAccess.getStateFormulaAccess().getGroup_1(), "rule__StateFormula__Group_1__0");
					put(grammarAccess.getStateFormulaAccess().getGroup_2(), "rule__StateFormula__Group_2__0");
					put(grammarAccess.getTimeInstantAccess().getGroup(), "rule__TimeInstant__Group__0");
					put(grammarAccess.getTimeInstantAccess().getGroup_1_0(), "rule__TimeInstant__Group_1_0__0");
					put(grammarAccess.getTimeInstantAccess().getGroup_1_1(), "rule__TimeInstant__Group_1_1__0");
					put(grammarAccess.getTimeInstantAccess().getGroup_1_2(), "rule__TimeInstant__Group_1_2__0");
					put(grammarAccess.getTimeIntervalAccess().getGroup(), "rule__TimeInterval__Group__0");
					put(grammarAccess.getRewardTimeInstantAccess().getGroup(), "rule__RewardTimeInstant__Group__0");
					put(grammarAccess.getProbabilityConstraintAccess().getGroup(), "rule__ProbabilityConstraint__Group__0");
					put(grammarAccess.getProbabilityConstraintAccess().getGroup_2_0(), "rule__ProbabilityConstraint__Group_2_0__0");
					put(grammarAccess.getConcentrationConstraintAccess().getGroup_0(), "rule__ConcentrationConstraint__Group_0__0");
					put(grammarAccess.getConcentrationConstraintAccess().getGroup_0_1(), "rule__ConcentrationConstraint__Group_0_1__0");
					put(grammarAccess.getPropertyInitialConditionAccess().getGroup(), "rule__PropertyInitialCondition__Group__0");
					put(grammarAccess.getUnitIntervalAccess().getGroup_1(), "rule__UnitInterval__Group_1__0");
					put(grammarAccess.getUnitIntervalAccess().getGroup_2(), "rule__UnitInterval__Group_2__0");
					put(grammarAccess.getDecimalAccess().getGroup(), "rule__Decimal__Group__0");
					put(grammarAccess.getDecimalAccess().getGroup_2(), "rule__Decimal__Group_2__0");
					put(grammarAccess.getDecimalExpAccess().getGroup(), "rule__DecimalExp__Group__0");
					put(grammarAccess.getDecimalExpAccess().getGroup_2(), "rule__DecimalExp__Group_2__0");
					put(grammarAccess.getQuantityAccess().getGroup(), "rule__Quantity__Group__0");
					put(grammarAccess.getConcentrationQuantityAccess().getGroup(), "rule__ConcentrationQuantity__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
					put(grammarAccess.getListAccess().getGroup_3(), "rule__List__Group_3__0");
					put(grammarAccess.getModelAccess().getMembersAssignment_1(), "rule__Model__MembersAssignment_1");
					put(grammarAccess.getImportStatementAccess().getImportedNamespaceAssignment_2(), "rule__ImportStatement__ImportedNamespaceAssignment_2");
					put(grammarAccess.getFunctionDefinitionAccess().getNameAssignment_2(), "rule__FunctionDefinition__NameAssignment_2");
					put(grammarAccess.getFunctionDefinitionAccess().getFunctionBodyAssignment_4(), "rule__FunctionDefinition__FunctionBodyAssignment_4");
					put(grammarAccess.getFunctionDefinitionAccess().getUsesAssignment_5_1(), "rule__FunctionDefinition__UsesAssignment_5_1");
					put(grammarAccess.getFunctionDefinitionAccess().getUsesAssignment_5_2_1(), "rule__FunctionDefinition__UsesAssignment_5_2_1");
					put(grammarAccess.getProcessBodyAccess().getParametersAssignment_3_0(), "rule__ProcessBody__ParametersAssignment_3_0");
					put(grammarAccess.getProcessBodyAccess().getParametersAssignment_3_1_1(), "rule__ProcessBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getProcessBodyAccess().getMembersAssignment_6(), "rule__ProcessBody__MembersAssignment_6");
					put(grammarAccess.getSystemBodyAccess().getParametersAssignment_3_0(), "rule__SystemBody__ParametersAssignment_3_0");
					put(grammarAccess.getSystemBodyAccess().getParametersAssignment_3_1_1(), "rule__SystemBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getSystemBodyAccess().getMembersAssignment_6(), "rule__SystemBody__MembersAssignment_6");
					put(grammarAccess.getPlasmidBodyAccess().getParametersAssignment_3_0(), "rule__PlasmidBody__ParametersAssignment_3_0");
					put(grammarAccess.getPlasmidBodyAccess().getParametersAssignment_3_1_1(), "rule__PlasmidBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getPlasmidBodyAccess().getMembersAssignment_6(), "rule__PlasmidBody__MembersAssignment_6");
					put(grammarAccess.getChromosomeBodyAccess().getParametersAssignment_3_0(), "rule__ChromosomeBody__ParametersAssignment_3_0");
					put(grammarAccess.getChromosomeBodyAccess().getParametersAssignment_3_1_1(), "rule__ChromosomeBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getChromosomeBodyAccess().getMembersAssignment_6(), "rule__ChromosomeBody__MembersAssignment_6");
					put(grammarAccess.getCellBodyAccess().getParametersAssignment_3_0(), "rule__CellBody__ParametersAssignment_3_0");
					put(grammarAccess.getCellBodyAccess().getParametersAssignment_3_1_1(), "rule__CellBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getCellBodyAccess().getMembersAssignment_6(), "rule__CellBody__MembersAssignment_6");
					put(grammarAccess.getRegionBodyAccess().getParametersAssignment_3_0(), "rule__RegionBody__ParametersAssignment_3_0");
					put(grammarAccess.getRegionBodyAccess().getParametersAssignment_3_1_1(), "rule__RegionBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getRegionBodyAccess().getMembersAssignment_6(), "rule__RegionBody__MembersAssignment_6");
					put(grammarAccess.getCustomFunctionBodyAccess().getFunctionTypeAssignment_1(), "rule__CustomFunctionBody__FunctionTypeAssignment_1");
					put(grammarAccess.getCustomFunctionBodyAccess().getParametersAssignment_3_0(), "rule__CustomFunctionBody__ParametersAssignment_3_0");
					put(grammarAccess.getCustomFunctionBodyAccess().getParametersAssignment_3_1_1(), "rule__CustomFunctionBody__ParametersAssignment_3_1_1");
					put(grammarAccess.getCustomFunctionBodyAccess().getMembersAssignment_6(), "rule__CustomFunctionBody__MembersAssignment_6");
					put(grammarAccess.getFunctionParameterMemberAccess().getTypeAssignment_0_0(), "rule__FunctionParameterMember__TypeAssignment_0_0");
					put(grammarAccess.getFunctionParameterMemberAccess().getCollectionAssignment_0_1_0(), "rule__FunctionParameterMember__CollectionAssignment_0_1_0");
					put(grammarAccess.getFunctionParameterMemberAccess().getTypeAssignment_0_1_2(), "rule__FunctionParameterMember__TypeAssignment_0_1_2");
					put(grammarAccess.getFunctionParameterMemberAccess().getNameAssignment_1(), "rule__FunctionParameterMember__NameAssignment_1");
					put(grammarAccess.getFunctionParameterMemberAccess().getScopeAssignment_2_1(), "rule__FunctionParameterMember__ScopeAssignment_2_1");
					put(grammarAccess.getFunctionUseMemberAccess().getTypeAssignment_0(), "rule__FunctionUseMember__TypeAssignment_0");
					put(grammarAccess.getFunctionUseMemberAccess().getNameAssignment_1(), "rule__FunctionUseMember__NameAssignment_1");
					put(grammarAccess.getDeviceDefinitionAccess().getNameAssignment_2(), "rule__DeviceDefinition__NameAssignment_2");
					put(grammarAccess.getDeviceDefinitionAccess().getPartsAssignment_9(), "rule__DeviceDefinition__PartsAssignment_9");
					put(grammarAccess.getDeviceDefinitionAccess().getInputAssignment_12_2(), "rule__DeviceDefinition__InputAssignment_12_2");
					put(grammarAccess.getDeviceDefinitionAccess().getOutputputAssignment_13_3(), "rule__DeviceDefinition__OutputputAssignment_13_3");
					put(grammarAccess.getDeviceDefinitionAccess().getMembersAssignment_16(), "rule__DeviceDefinition__MembersAssignment_16");
					put(grammarAccess.getProcessInstantiationAccess().getNameAssignment_2(), "rule__ProcessInstantiation__NameAssignment_2");
					put(grammarAccess.getProcessInstantiationAccess().getConstructorAssignment_3_2(), "rule__ProcessInstantiation__ConstructorAssignment_3_2");
					put(grammarAccess.getProcessInstantiationAccess().getParametersAssignment_3_4_0(), "rule__ProcessInstantiation__ParametersAssignment_3_4_0");
					put(grammarAccess.getProcessInstantiationAccess().getParametersAssignment_3_4_1_1(), "rule__ProcessInstantiation__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getSystemInstantiationAccess().getNameAssignment_2(), "rule__SystemInstantiation__NameAssignment_2");
					put(grammarAccess.getSystemInstantiationAccess().getConstructorAssignment_3_2(), "rule__SystemInstantiation__ConstructorAssignment_3_2");
					put(grammarAccess.getSystemInstantiationAccess().getParametersAssignment_3_4_0(), "rule__SystemInstantiation__ParametersAssignment_3_4_0");
					put(grammarAccess.getSystemInstantiationAccess().getParametersAssignment_3_4_1_1(), "rule__SystemInstantiation__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getPlasmidInstantiationAccess().getNameAssignment_2(), "rule__PlasmidInstantiation__NameAssignment_2");
					put(grammarAccess.getPlasmidInstantiationAccess().getConstructorAssignment_3_2(), "rule__PlasmidInstantiation__ConstructorAssignment_3_2");
					put(grammarAccess.getPlasmidInstantiationAccess().getParametersAssignment_3_4_0(), "rule__PlasmidInstantiation__ParametersAssignment_3_4_0");
					put(grammarAccess.getPlasmidInstantiationAccess().getParametersAssignment_3_4_1_1(), "rule__PlasmidInstantiation__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getChromosomeInstantiationAccess().getNameAssignment_2(), "rule__ChromosomeInstantiation__NameAssignment_2");
					put(grammarAccess.getChromosomeInstantiationAccess().getConstructorAssignment_3_2(), "rule__ChromosomeInstantiation__ConstructorAssignment_3_2");
					put(grammarAccess.getChromosomeInstantiationAccess().getParametersAssignment_3_4_0(), "rule__ChromosomeInstantiation__ParametersAssignment_3_4_0");
					put(grammarAccess.getChromosomeInstantiationAccess().getParametersAssignment_3_4_1_1(), "rule__ChromosomeInstantiation__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getCellInstantiationAccess().getNameAssignment_2(), "rule__CellInstantiation__NameAssignment_2");
					put(grammarAccess.getCellInstantiationAccess().getConstructorAssignment_3_2(), "rule__CellInstantiation__ConstructorAssignment_3_2");
					put(grammarAccess.getCellInstantiationAccess().getParametersAssignment_3_4_0(), "rule__CellInstantiation__ParametersAssignment_3_4_0");
					put(grammarAccess.getCellInstantiationAccess().getParametersAssignment_3_4_1_1(), "rule__CellInstantiation__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getVariableComplexAccess().getComponentsAssignment_1(), "rule__VariableComplex__ComponentsAssignment_1");
					put(grammarAccess.getVariableComplexAccess().getComponentsAssignment_2_1(), "rule__VariableComplex__ComponentsAssignment_2_1");
					put(grammarAccess.getVariableAttributeAccess().getNameAssignment_1_0(), "rule__VariableAttribute__NameAssignment_1_0");
					put(grammarAccess.getVariableAttributeAccess().getComplexAssignment_1_1(), "rule__VariableAttribute__ComplexAssignment_1_1");
					put(grammarAccess.getVariableAttributeAccess().getAttributeAssignment_3(), "rule__VariableAttribute__AttributeAssignment_3");
					put(grammarAccess.getVariableDefinitionAccess().getDefinitionAssignment_1(), "rule__VariableDefinition__DefinitionAssignment_1");
					put(grammarAccess.getVariableDefinitionAccess().getQualifierAssignment_2_1(), "rule__VariableDefinition__QualifierAssignment_2_1");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getTypeAssignment_1(), "rule__VariableDefinitionBuiltIn__TypeAssignment_1");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getNameAssignment_2_0(), "rule__VariableDefinitionBuiltIn__NameAssignment_2_0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getComplexAssignment_2_1(), "rule__VariableDefinitionBuiltIn__ComplexAssignment_2_1");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getConstructorAssignment_3_2(), "rule__VariableDefinitionBuiltIn__ConstructorAssignment_3_2");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getParametersAssignment_3_4_0(), "rule__VariableDefinitionBuiltIn__ParametersAssignment_3_4_0");
					put(grammarAccess.getVariableDefinitionBuiltInAccess().getParametersAssignment_3_4_1_1(), "rule__VariableDefinitionBuiltIn__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getTypeAssignment_1(), "rule__VariableDefinitionUserDefined__TypeAssignment_1");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getNameAssignment_2(), "rule__VariableDefinitionUserDefined__NameAssignment_2");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getConstructorAssignment_3_2(), "rule__VariableDefinitionUserDefined__ConstructorAssignment_3_2");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getParametersAssignment_3_4_0(), "rule__VariableDefinitionUserDefined__ParametersAssignment_3_4_0");
					put(grammarAccess.getVariableDefinitionUserDefinedAccess().getParametersAssignment_3_4_1_1(), "rule__VariableDefinitionUserDefined__ParametersAssignment_3_4_1_1");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getCollectionAssignment_1_0(), "rule__VariableDefinitionCollection__CollectionAssignment_1_0");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getTypeAssignment_1_2(), "rule__VariableDefinitionCollection__TypeAssignment_1_2");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getNameAssignment_1_4(), "rule__VariableDefinitionCollection__NameAssignment_1_4");
					put(grammarAccess.getVariableDefinitionCollectionAccess().getValueAssignment_2_1(), "rule__VariableDefinitionCollection__ValueAssignment_2_1");
					put(grammarAccess.getVariableDefinitionBasicAccess().getTypeAssignment_1(), "rule__VariableDefinitionBasic__TypeAssignment_1");
					put(grammarAccess.getVariableDefinitionBasicAccess().getNameAssignment_2(), "rule__VariableDefinitionBasic__NameAssignment_2");
					put(grammarAccess.getVariableDefinitionBasicAccess().getExpressionAssignment_4(), "rule__VariableDefinitionBasic__ExpressionAssignment_4");
					put(grammarAccess.getParameterAssignmentAccess().getNameAssignment_0(), "rule__ParameterAssignment__NameAssignment_0");
					put(grammarAccess.getParameterAssignmentAccess().getValueAssignment_2(), "rule__ParameterAssignment__ValueAssignment_2");
					put(grammarAccess.getVariableAssignmentAccess().getVariableAssignment_1(), "rule__VariableAssignment__VariableAssignment_1");
					put(grammarAccess.getVariableAssignmentAccess().getExpressionAssignment_3(), "rule__VariableAssignment__ExpressionAssignment_3");
					put(grammarAccess.getVariableExpressionAccess().getMembersAssignment_1(), "rule__VariableExpression__MembersAssignment_1");
					put(grammarAccess.getVariableExpressionAccess().getMembersAssignment_2_1(), "rule__VariableExpression__MembersAssignment_2_1");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getVariableAssignment_0_1(), "rule__AtomicVariableExpressionObject__VariableAssignment_0_1");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getAttributeAssignment_1(), "rule__AtomicVariableExpressionObject__AttributeAssignment_1");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getComplexAssignment_2(), "rule__AtomicVariableExpressionObject__ComplexAssignment_2");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getValueAssignment_3(), "rule__AtomicVariableExpressionObject__ValueAssignment_3");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getQuantityAssignment_4(), "rule__AtomicVariableExpressionObject__QuantityAssignment_4");
					put(grammarAccess.getAtomicVariableExpressionObjectAccess().getStringAssignment_5(), "rule__AtomicVariableExpressionObject__StringAssignment_5");
					put(grammarAccess.getCompoundVariableExpressionObjectAccess().getListAssignment_1(), "rule__CompoundVariableExpressionObject__ListAssignment_1");
					put(grammarAccess.getRuleDefinitionAccess().getNameAssignment_2(), "rule__RuleDefinition__NameAssignment_2");
					put(grammarAccess.getRuleDefinitionAccess().getLhsAssignment_4_0(), "rule__RuleDefinition__LhsAssignment_4_0");
					put(grammarAccess.getRuleDefinitionAccess().getLhsAssignment_4_1_1(), "rule__RuleDefinition__LhsAssignment_4_1_1");
					put(grammarAccess.getRuleDefinitionAccess().getReversibleAssignment_5_1(), "rule__RuleDefinition__ReversibleAssignment_5_1");
					put(grammarAccess.getRuleDefinitionAccess().getRhsAssignment_6_0(), "rule__RuleDefinition__RhsAssignment_6_0");
					put(grammarAccess.getRuleDefinitionAccess().getRhsAssignment_6_1_1(), "rule__RuleDefinition__RhsAssignment_6_1_1");
					put(grammarAccess.getATGCDefinitionAccess().getCommandAssignment_2(), "rule__ATGCDefinition__CommandAssignment_2");
					put(grammarAccess.getATGCDefinitionAccess().getArgumentsAssignment_4(), "rule__ATGCDefinition__ArgumentsAssignment_4");
					put(grammarAccess.getATGCDefinitionAccess().getArgumentsAssignment_5_1(), "rule__ATGCDefinition__ArgumentsAssignment_5_1");
					put(grammarAccess.getPropertyDefinitionAccess().getPropertyAssignment_2(), "rule__PropertyDefinition__PropertyAssignment_2");
					put(grammarAccess.getProbabilityPropertyAccess().getStateFormula1Assignment_1(), "rule__ProbabilityProperty__StateFormula1Assignment_1");
					put(grammarAccess.getProbabilityPropertyAccess().getIsEventuallyAssignment_2_0_0_0_0(), "rule__ProbabilityProperty__IsEventuallyAssignment_2_0_0_0_0");
					put(grammarAccess.getProbabilityPropertyAccess().getIsNeverAssignment_2_0_0_0_1(), "rule__ProbabilityProperty__IsNeverAssignment_2_0_0_0_1");
					put(grammarAccess.getProbabilityPropertyAccess().getIsAlwaysAssignment_2_0_0_0_2(), "rule__ProbabilityProperty__IsAlwaysAssignment_2_0_0_0_2");
					put(grammarAccess.getProbabilityPropertyAccess().getIsUntilThenAssignment_2_0_0_1_0_0(), "rule__ProbabilityProperty__IsUntilThenAssignment_2_0_0_1_0_0");
					put(grammarAccess.getProbabilityPropertyAccess().getIsFollowedByAssignment_2_0_0_1_0_1(), "rule__ProbabilityProperty__IsFollowedByAssignment_2_0_0_1_0_1");
					put(grammarAccess.getProbabilityPropertyAccess().getStateFormula2Assignment_2_0_0_1_1(), "rule__ProbabilityProperty__StateFormula2Assignment_2_0_0_1_1");
					put(grammarAccess.getProbabilityPropertyAccess().getTimeInstantAssignment_2_0_1_0(), "rule__ProbabilityProperty__TimeInstantAssignment_2_0_1_0");
					put(grammarAccess.getProbabilityPropertyAccess().getTimeIntervalAssignment_2_0_1_1(), "rule__ProbabilityProperty__TimeIntervalAssignment_2_0_1_1");
					put(grammarAccess.getProbabilityPropertyAccess().getIsSteadyStateAssignment_2_1_0(), "rule__ProbabilityProperty__IsSteadyStateAssignment_2_1_0");
					put(grammarAccess.getProbabilityPropertyAccess().getIsInfinitelyOftenAssignment_2_1_1(), "rule__ProbabilityProperty__IsInfinitelyOftenAssignment_2_1_1");
					put(grammarAccess.getProbabilityPropertyAccess().getProbabilityConstraintAssignment_3(), "rule__ProbabilityProperty__ProbabilityConstraintAssignment_3");
					put(grammarAccess.getProbabilityPropertyAccess().getInitialConditionsAssignment_4_1(), "rule__ProbabilityProperty__InitialConditionsAssignment_4_1");
					put(grammarAccess.getProbabilityPropertyAccess().getInitialConditionsAssignment_4_2_1(), "rule__ProbabilityProperty__InitialConditionsAssignment_4_2_1");
					put(grammarAccess.getRewardPropertyAccess().getNameAssignment_3(), "rule__RewardProperty__NameAssignment_3");
					put(grammarAccess.getRewardPropertyAccess().getTimeInstantAssignment_5(), "rule__RewardProperty__TimeInstantAssignment_5");
					put(grammarAccess.getRewardPropertyAccess().getConcentrationConstraintAssignment_7(), "rule__RewardProperty__ConcentrationConstraintAssignment_7");
					put(grammarAccess.getRewardPropertyAccess().getInitialConditionsAssignment_8_1(), "rule__RewardProperty__InitialConditionsAssignment_8_1");
					put(grammarAccess.getRewardPropertyAccess().getInitialConditionsAssignment_8_2_1(), "rule__RewardProperty__InitialConditionsAssignment_8_2_1");
					put(grammarAccess.getStateExpressionAccess().getNameAssignment_1(), "rule__StateExpression__NameAssignment_1");
					put(grammarAccess.getStateExpressionAccess().getOperatorAssignment_2(), "rule__StateExpression__OperatorAssignment_2");
					put(grammarAccess.getStateExpressionAccess().getConcentrationQuantityAssignment_3(), "rule__StateExpression__ConcentrationQuantityAssignment_3");
					put(grammarAccess.getStateFormulaAccess().getFormulaAssignment_0_1(), "rule__StateFormula__FormulaAssignment_0_1");
					put(grammarAccess.getStateFormulaAccess().getAtomicFormulaAssignment_0_2(), "rule__StateFormula__AtomicFormulaAssignment_0_2");
					put(grammarAccess.getStateFormulaAccess().getIsNegationAssignment_1_1(), "rule__StateFormula__IsNegationAssignment_1_1");
					put(grammarAccess.getStateFormulaAccess().getNegatedFormulaAssignment_1_2(), "rule__StateFormula__NegatedFormulaAssignment_1_2");
					put(grammarAccess.getStateFormulaAccess().getLeftFormulaAssignment_2_1(), "rule__StateFormula__LeftFormulaAssignment_2_1");
					put(grammarAccess.getStateFormulaAccess().getIsConjunctionAssignment_2_2_0(), "rule__StateFormula__IsConjunctionAssignment_2_2_0");
					put(grammarAccess.getStateFormulaAccess().getIsDisjunctionAssignment_2_2_1(), "rule__StateFormula__IsDisjunctionAssignment_2_2_1");
					put(grammarAccess.getStateFormulaAccess().getIsImplicationAssignment_2_2_2(), "rule__StateFormula__IsImplicationAssignment_2_2_2");
					put(grammarAccess.getStateFormulaAccess().getRightFormulaAssignment_2_3(), "rule__StateFormula__RightFormulaAssignment_2_3");
					put(grammarAccess.getTimeInstantAccess().getIsEqualToAssignment_1_0_0(), "rule__TimeInstant__IsEqualToAssignment_1_0_0");
					put(grammarAccess.getTimeInstantAccess().getTimeInstantAssignment_1_0_1(), "rule__TimeInstant__TimeInstantAssignment_1_0_1");
					put(grammarAccess.getTimeInstantAccess().getIsLessThanOrEqualAssignment_1_1_0(), "rule__TimeInstant__IsLessThanOrEqualAssignment_1_1_0");
					put(grammarAccess.getTimeInstantAccess().getTimeInstantAssignment_1_1_1(), "rule__TimeInstant__TimeInstantAssignment_1_1_1");
					put(grammarAccess.getTimeInstantAccess().getIsGreaterThanOrEqualAssignment_1_2_0(), "rule__TimeInstant__IsGreaterThanOrEqualAssignment_1_2_0");
					put(grammarAccess.getTimeInstantAccess().getTimeInstantAssignment_1_2_1(), "rule__TimeInstant__TimeInstantAssignment_1_2_1");
					put(grammarAccess.getTimeInstantAccess().getTimeUnitAssignment_2(), "rule__TimeInstant__TimeUnitAssignment_2");
					put(grammarAccess.getTimeIntervalAccess().getLowerBoundAssignment_3(), "rule__TimeInterval__LowerBoundAssignment_3");
					put(grammarAccess.getTimeIntervalAccess().getUpperBoundAssignment_5(), "rule__TimeInterval__UpperBoundAssignment_5");
					put(grammarAccess.getTimeIntervalAccess().getTimeUnitAssignment_7(), "rule__TimeInterval__TimeUnitAssignment_7");
					put(grammarAccess.getRewardTimeInstantAccess().getIsEqualToAssignment_1_0(), "rule__RewardTimeInstant__IsEqualToAssignment_1_0");
					put(grammarAccess.getRewardTimeInstantAccess().getIsLessThanOrEqualAssignment_1_1(), "rule__RewardTimeInstant__IsLessThanOrEqualAssignment_1_1");
					put(grammarAccess.getRewardTimeInstantAccess().getTimeValueAssignment_2(), "rule__RewardTimeInstant__TimeValueAssignment_2");
					put(grammarAccess.getRewardTimeInstantAccess().getTimeUnitAssignment_3(), "rule__RewardTimeInstant__TimeUnitAssignment_3");
					put(grammarAccess.getProbabilityConstraintAccess().getOperatorAssignment_2_0_0(), "rule__ProbabilityConstraint__OperatorAssignment_2_0_0");
					put(grammarAccess.getProbabilityConstraintAccess().getProbabilityAssignment_2_0_1(), "rule__ProbabilityConstraint__ProbabilityAssignment_2_0_1");
					put(grammarAccess.getProbabilityConstraintAccess().getHasUnknownProbabilityAssignment_2_1(), "rule__ProbabilityConstraint__HasUnknownProbabilityAssignment_2_1");
					put(grammarAccess.getConcentrationConstraintAccess().getOperatorAssignment_0_1_0(), "rule__ConcentrationConstraint__OperatorAssignment_0_1_0");
					put(grammarAccess.getConcentrationConstraintAccess().getValueAssignment_0_1_1(), "rule__ConcentrationConstraint__ValueAssignment_0_1_1");
					put(grammarAccess.getConcentrationConstraintAccess().getUnitAssignment_0_1_2(), "rule__ConcentrationConstraint__UnitAssignment_0_1_2");
					put(grammarAccess.getConcentrationConstraintAccess().getIsUnknownAssignment_1(), "rule__ConcentrationConstraint__IsUnknownAssignment_1");
					put(grammarAccess.getPropertyInitialConditionAccess().getVariableAssignment_1(), "rule__PropertyInitialCondition__VariableAssignment_1");
					put(grammarAccess.getPropertyInitialConditionAccess().getValueAssignment_3(), "rule__PropertyInitialCondition__ValueAssignment_3");
					put(grammarAccess.getQuantityAccess().getValueAssignment_1(), "rule__Quantity__ValueAssignment_1");
					put(grammarAccess.getQuantityAccess().getUnitsAssignment_2(), "rule__Quantity__UnitsAssignment_2");
					put(grammarAccess.getConcentrationQuantityAccess().getValueAssignment_1(), "rule__ConcentrationQuantity__ValueAssignment_1");
					put(grammarAccess.getConcentrationQuantityAccess().getUnitAssignment_2(), "rule__ConcentrationQuantity__UnitAssignment_2");
					put(grammarAccess.getListAccess().getEntriesAssignment_2(), "rule__List__EntriesAssignment_2");
					put(grammarAccess.getListAccess().getEntriesAssignment_3_1(), "rule__List__EntriesAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			roadblock.xtext.ibl.ui.contentassist.antlr.internal.InternalIblParser typedParser = (roadblock.xtext.ibl.ui.contentassist.antlr.internal.InternalIblParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public IblGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IblGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
