/*
 * generated by Xtext
 */
package roadblock.xtext.ibl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractIblValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(roadblock.xtext.ibl.ibl.IblPackage.eINSTANCE);
		return result;
	}
}
